implemented dao and service for model classes (Actor, Movie, Country)…
mate-academy/hibernate-relations-hw pull request #57
Opened 2021-08-01 11:05 UTC by Daniel1004K

…, did connection with DB with Hibernate

2021-08-01 18:00 UTC, SeReNb26 requested changes
qwerty123

2021-08-02 10:51 UTC, SeReNb26 requested changes

2021-08-02 10:51 UTC, SeReNb26 commented on src/main/java/mate/academy/hibernate/relations/Main.java
> +                HibernateUtil.getSessionFactory());
Лучше было оставить переменную sessionFactory, чтобы не вызывать каждый раз функцию на получение этого объекта в  конструкторах Dao.

2021-08-02 11:01 UTC, SeReNb26 approved these changes

2021-08-02 11:23 UTC, KseniiaMakarova requested changes

2021-08-02 11:23 UTC, KseniiaMakarova commented on src/main/java/mate/academy/hibernate/relations/Main.java
> +        CountryService countryService = new CountryServiceImpl(countryDao);
```suggestion
        CountryService countryService = new CountryServiceImpl(new CountryDaoImpl(sessionFactory));
```
same for other services - if we can fit it in 100 characters - let's do it

2021-08-02 11:32 UTC, KseniiaMakarova approved these changes

2023-04-07 12:46 UTC, closed without merging