init commit
mate-academy/hibernate-relations-hw pull request #648
Opened 2023-08-14 14:20 UTC by Denis-Balako

2023-08-14 15:17 UTC, Dimagaa requested changes
Good solution! I have a few suggestions

You should create a constructor for DataProccessingException that accepts a String and a Throwable, and then use it in the catch blocks

2023-08-14 15:17 UTC, Dimagaa commented on src/main/java/mate/academy/hibernate/relations/dao/impl/ActorDaoImpl.java
> +            throw new DataProcessingException("Can't add actor " + actor + " to DB.");
Pass caught exception in DataProccessingException constructor
```suggestion
            throw new DataProcessingException("Can't add actor " + actor + " to DB.", e);
```

2023-08-14 15:51 UTC, Dimagaa approved these changes
Well done!)

2023-08-14 16:06 UTC, vovasalyha requested changes
Great work, but please use explicit mappings of your collections, do not rely on default Hibernate's mapping.

2023-08-14 16:06 UTC, vovasalyha commented on src/main/java/mate/academy/hibernate/relations/model/Actor.java
> +    @ManyToOne
Add `@JoinColumn`.

2023-08-14 16:06 UTC, vovasalyha commented on src/main/java/mate/academy/hibernate/relations/model/Movie.java
> +    @ManyToMany(fetch = FetchType.EAGER)
Add `@JoinTable`.

2023-08-15 07:47 UTC, nacenik approved these changes
LGTM! 👍

2026-05-02 16:39 UTC, closed without merging