Implemented model, dao and service level. Created custom unchecked ex…
mate-academy/hibernate-relations-hw pull request #652
Opened 2023-08-14 15:35 UTC by OlegStashkiv

…ception DataProcessingException. Added hibernate.cfg.xml configuration file.

2023-08-14 19:20 UTC, DmytroV95 requested changes
Gj! Lets improve it!

2023-08-14 19:20 UTC, DmytroV95 commented on src/main/java/mate/academy/hibernate/relations/dao/impl/ActorDaoImpl.java
> +        }
We don't need transaction in methods where data is not changed. Also, use try-with-resources to close session to make your code more readable.

2023-08-14 19:20 UTC, DmytroV95 commented on src/main/java/mate/academy/hibernate/relations/dao/impl/CountryDaoImpl.java
> +        }
We don't need transaction in methods where data is not changed. Also, use try-with-resources to close session to make your code more readable.

2023-08-14 19:20 UTC, DmytroV95 commented on src/main/java/mate/academy/hibernate/relations/dao/impl/MovieDaoImpl.java
> +        }
We don't need transaction in methods where data is not changed. Also, use try-with-resources to close session to make your code more readable.

2023-08-14 19:20 UTC, DmytroV95 commented on src/main/java/mate/academy/hibernate/relations/model/Movie.java
> +    @ManyToMany(fetch = FetchType.EAGER)
Use JoinTable and JoinColumn annotation to make  columns and table name in new table that will be created in same naming style as basic tables.

2023-08-14 19:20 UTC, DmytroV95 commented on src/main/java/mate/academy/hibernate/relations/service/impl/ActorServiceImpl.java
> +        return actorDao.get(id).orElseThrow();
Specify an exception that will be thrown, and add its description.

2023-08-14 19:20 UTC, DmytroV95 commented on src/main/java/mate/academy/hibernate/relations/service/impl/CountryServiceImpl.java
> +        return countryDao.get(id).orElseThrow();
Specify an exception that will be thrown, and add its description.

2023-08-14 19:20 UTC, DmytroV95 commented on src/main/java/mate/academy/hibernate/relations/service/impl/MovieServiceImpl.java
> +        return movieDao.get(id).orElseThrow();
Specify an exception that will be thrown, and add its description.

2023-08-14 19:20 UTC, DmytroV95 commented on src/main/resources/hibernate.cfg.xml
> +</hibernate-configuration>
add an empty line at the end

2023-08-15 07:32 UTC, nacenik requested changes
Good solution, let's improve it :)

2023-08-15 07:32 UTC, nacenik commented on src/main/java/mate/academy/hibernate/relations/Main.java
> +        CountryService countryService = new CountryServiceImpl(sessionFactory);
pass Dao as a parameter to the service, not a session factory. Fix it in all places

2023-08-15 07:32 UTC, nacenik commented on src/main/java/mate/academy/hibernate/relations/dao/impl/ActorDaoImpl.java
> +            throw new DataProcessingException("Can`t get actor from DB with id: " + id);
Pass exception as a second parameter too. Don't forget about stack trace. Fix it in all places

2023-08-15 07:32 UTC, nacenik commented on src/main/java/mate/academy/hibernate/relations/exception/DataProcessingException.java
> +public class DataProcessingException extends RuntimeException {
you should have a constructor with 2 parameters - message and exception.

2023-08-15 07:32 UTC, nacenik commented on src/main/java/mate/academy/hibernate/relations/model/Actor.java
> +    @ManyToOne
add joincolumn

2023-08-15 09:37 UTC, Vasul-Pankiv approved these changes

2026-05-21 07:58 UTC, closed without merging