Fix lazy initialized actors exception
mate-academy/hibernate-relations-hw pull request #697
Opened 2023-09-06 16:14 UTC by sarakhmen

Applying the next [improvement](https://prnt.sc/5TRAgTZ2JJOy)

2023-09-06 16:43 UTC, boroda4436 requested changes

2023-09-06 16:43 UTC, boroda4436 commented on src/test/java/mate/academy/hibernate/relations/dao/impl/MovieDaoImplTest.java
> +        }catch (Exception e){
```suggestion
        } catch (Exception e) {
```

2023-09-06 16:43 UTC, boroda4436 commented on src/test/java/mate/academy/hibernate/relations/dao/impl/MovieDaoImplTest.java
> +            Hibernate.initialize(movie.getActors());
`Hibernate.initialize` is not the best approach to fix LazyInitializationException. Can we use join fetch here?

2023-09-06 16:43 UTC, boroda4436 commented on src/test/java/mate/academy/hibernate/relations/dao/impl/MovieDaoImplTest.java
> +            throw new RuntimeException(e);
add some informative message as a first param to the constructor

2023-09-07 11:28 UTC, boroda4436 approved these changes

2023-09-08 04:33 UTC, Nick97-git approved these changes

2023-09-08 04:33 UTC, Nick97-git commented on src/test/java/mate/academy/hibernate/relations/dao/impl/MovieDaoImplTest.java
> +    private Optional<Movie> getMovie(Long id) {
```suggestion
    private Optional<Movie> getMovieById(Long id) {
```

2023-09-11 10:51 UTC, merged