done homework
mate-academy/hibernate-relations-hw pull request #841
Opened 2024-02-10 17:36 UTC by RomanSoproniuk

2024-02-11 18:10 UTC, RomanSoproniuk commented on src/main/java/mate/academy/hibernate/relations/service/impl/CountryServiceImpl.java
> +        return countryDao.get(id).orElseThrow();
i understand, but i have this message on Dao Layer

2024-02-11 18:13 UTC, RomanSoproniuk commented on src/main/java/mate/academy/hibernate/relations/service/impl/CountryServiceImpl.java
> +        return countryDao.get(id).orElseThrow();
Have i do duplicate?

2024-02-11 18:28 UTC, okuzan requested changes

2024-02-11 18:28 UTC, okuzan commented on src/main/java/mate/academy/hibernate/relations/service/impl/MovieServiceImpl.java
> +                new DataProcessingException("Movie by " + id + "not found."));
data processing is for dao layer, on service layer throw EntityNotFoundException - it's in a library, don't create your own

2024-02-14 11:34 UTC, Vasul-Pankiv approved these changes

2025-03-22 20:10 UTC, closed without merging